# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-04 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasource', models.CharField(max_length=200, verbose_name='Datasource')),
                ('campaign', models.CharField(max_length=200, verbose_name='Campaign')),
                ('clicks', models.IntegerField(verbose_name='Clicks')),
                ('impressions', models.IntegerField(verbose_name='Impressions')),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Advertising Data',
            },
        ),
    ]
